name: xdggs_dev
channels:
  - conda-forge
dependencies:
  - xarray
  - healpy
  - ruff
  - pytest
  - h5netcdf
  - netcdf4
  - pooch
  - matplotlib-base
  - shapely
  - tqdm
  - pys2index
  - gdal==3.6.2
  - proj==9.1.0
  - numpy==1.24.1
  - pip
  - pip:
      - h3ronpy
      - pymp-pypi
